### ISSUE TITLE
Support LFS

### ISSUE THREAD

**Issue by 6543** [42wim/caddy-gitea#1]
https://github.com/42wim/caddy-gitea/blob/136c600e2570179d02e8bd45c9897786c36d0f9c/pkg/gitea/gitea.go#L129-L130

-> https://codeberg.org/Codeberg/pages-server/pulls/114

**Comment by 42wim** [comment]
Hi @6543 thanks, but it already supports LFS

`giteaURL, err = url.JoinPath(c.serverURL+"/api/v1/repos/", owner, repo, "media", filepath)`

I'm not sure why that comment is there though :)
