### ISSUE TITLE
[Bugs?] http://org.localhost:3000/index.html cannot display pictures _images/image.png.

### ISSUE THREAD

**Issue by editfund-founder** [42wim/caddy-gitea#2]
# Windows
| URL |  |
| --- | --- |
| http://org.localhost:3000/index.html | `It works` |
| http://org.localhost:3000/image.png | `It works` |
| http://org.localhost:3000/_images/image.png | `404 error` |
# Linux
| URL |  |
| --- | --- |
| http://org.localhost:3000/index.html | `It works` |
| http://org.localhost:3000/image.png | `It works` |
| http://org.localhost:3000/_images/image.png | `It works` |

However, `http://org.localhost:3000/index.html` cannot display pictures `_images/image.png`.

**Comment by editfund-founder** [comment]
Use:
- [gin](https://github.com/gin-gonic/gin)
- [tea](https://gitea.com/gitea/tea)

I have developed another Pages service for gitea, named `page-runner`.

**Comment by 42wim** [comment]
Just to be sure, the bug is when running gitea under windows and not your client/browser, right?
