### ISSUE TITLE
Token?

### ISSUE THREAD

**Issue by SSP6904** [42wim/caddy-gitea#3]
I'm setting up my caddy server for the plugin, however I don't get the `token` variable for the `Caddyfile`.

Wasn't I supposed to the find that in Gitea somewhere?

**Comment by 42wim** [comment]
Token is a token created in gitea that has the necessary rights to read the private/public repo's that you want to expose.
(so you make or use a user that has the necessary rights)

I'll make that more clear in the README

**Comment by SSP6904** [comment]
Oh okay. 👍
