### ISSUE TITLE
make your docs understanable

### ISSUE THREAD

**Issue by phonkd** [42wim/caddy-gitea#5]
I'm having trouble understanding how to setup the caddy server with the plugins etc.
Did I understand correctly that i have to for each update rebuild my own caddy?

**Comment by 42wim** [comment]
For each update of what?
When caddy-gitea releases an update yes
When gitea releases an update no (unless they break API)
When caddy releases an update no (unless it's a security update)

**Comment by phonkd** [comment]
k
